spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/db_project?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC}
#    url: jdbc:mysql://localhost:3306/db_project?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
mail:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  host: smtp.yandex.ru
  port: 465
  protocol: smtps
  debug: true

server:
  port: ${PORT:8080}

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005

send:
  localhost: akbashev-java-skillbox.herokuapp.com
#  localhost: localhost:8080

production:
  cloud_name: "hmslac4qf"
  api_key: "773262953886412"
  api_secret: "qLdez354SSbhbMhALMQ6tOE3MaM"
  secure: true