spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_project?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/db_project?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC}
    username: root
    password: P@$$w0rd
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  mail:
    username: fo4test@yandex.ru
    password: p@$$w0rd
    host: smtp.yandex.ru
    port: 465
    protocol: smtps

server:
  port: ${PORT:8080}

mail:
  debug: true

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005

send:
#  localhost: akbashev-java-skillbox.herokuapp.com
  localhost: localhost:8080

production:
  cloud_name: "hmslac4qf"
  api_key: "773262953886412"
  api_secret: "qLdez354SSbhbMhALMQ6tOE3MaM"
  secure: true